/**
 * Class representing a sales representative.
 */
public class SalesRepresentative {

    private int numberOfSales;
    private double quotaPerSale;
    private double revenue;

    /**
     * Constructor for SalesRepresentative.
     * 
     * @param numberOfSales Number of sales made by the representative.
     * @param quotaPerSale  Quota per sale for the representative.
     */
    public SalesRepresentative(int numberOfSales, double quotaPerSale) {
        this.numberOfSales = numberOfSales;
        this.quotaPerSale = quotaPerSale;
        this.revenue = calculateRevenue();
    }

    /**
     * Calculate and return the revenue generated by the representative.
     * 
     * @return Revenue generated.
     */
    private double calculateRevenue() {
        return numberOfSales * quotaPerSale;
    }

    /**
     * Get the revenue generated by the representative.
     * 
     * @return Revenue.
     */
    public double getRevenue() {
        return revenue;
    }

    @Override
    public String toString() {
        return "SalesRepresentative{" +
                "numberOfSales=" + numberOfSales +
                ", quotaPerSale=" + quotaPerSale +
                ", revenue=" + revenue +
                '}';
    }
}
